name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set git config
        run: |
          git config --global pull.rebase false
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Pull to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hub https://robyramos:$HF_TOKEN@huggingface.co/spaces/robyramos/smart
          git fetch hub
          git merge --allow-unrelated-histories hub/main
          
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://robyramos:$HF_TOKEN@huggingface.co/spaces/robyramos/smart main
